
[buildpack]
id = "org.cloudfoundry.conda"
name = "Conda Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "miniconda3"
name = "Miniconda3"
sha256 = "e5e5b4cd2a918e0e96b395534222773f7241dc59d776db1b9f7fedfcb489157a"
source = "https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh"
source_sha256 = "e5e5b4cd2a918e0e96b395534222773f7241dc59d776db1b9f7fedfcb489157a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh"
version = "4.5.12"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
