api = "0.5"

[buildpack]
id = "paketo-community/miniconda"
name = "Paketo Miniconda Buildpack"

[metadata]
include-files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
pre-package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "miniconda3"
name = "Miniconda"
sha256 = "a23fcffe97690d3bbcd34cda798c3a3318e0f35d863c5d4aca3fc983fe8450b7"
source = "https://github.com/conda/conda/archive/4.7.12.tar.gz"
source_sha256 = "a23fcffe97690d3bbcd34cda798c3a3318e0f35d863c5d4aca3fc983fe8450b7"
stacks = ["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://repo.continuum.io/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh"
version = "4.7.12"

[[metadata.dependency_deprecation_dates]]
date = 2023-06-27T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0537/"
name = "miniconda3"
version_line = "4.7.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
