
[buildpack]
id = "org.cloudfoundry.buildpacks.conda"
name = "Conda Buildpack"
version = "0.0.1"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.dependencies]]
id = "miniconda2"
name = "Miniconda2"
sha256 = "bb03ebb9057b0ffcdd5b0192ef44b4c414a5cc25e05d3f319b66e44d2a3b0146"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://repo.continuum.io/miniconda/Miniconda2-4.5.12-Linux-x86_64.sh"
version = "4.5.12"

[[metadata.dependencies]]
id = "miniconda3"
name = "Miniconda3"
sha256 = "e5e5b4cd2a918e0e96b395534222773f7241dc59d776db1b9f7fedfcb489157a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh"
version = "4.5.12"
