api = "0.2"

[buildpack]
id = "org.cloudfoundry.conda"
name = "Conda Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "miniconda3"
name = "Miniconda"
sha256 = "bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2"
source = "https://github.com/conda/conda/archive/4.7.12.1.tar.gz"
source_sha256 = "bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh"
version = "4.7.12.1"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
